package pe.edu.uni.educate.view;

import javax.swing.JInternalFrame;
import pe.edu.uni.educate.dto.EmpleadoDto;
import pe.edu.uni.educate.util.Session;

public class MainView extends javax.swing.JFrame {

	/**
	 * Creates new form MainView
	 */
	public MainView() {
		initComponents();
		this.setExtendedState(MAXIMIZED_BOTH);
		this.establecerTitulo();
	}

	private void establecerTitulo() {
		// Obtener el objeto usuario.
		EmpleadoDto bean = (EmpleadoDto) Session.get("usuario");
		// Ahora el titulo
		String titulo = "Educate con los mejores (" + bean.getUsuario() + ")";
		this.setTitle(titulo);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        menuMaestros = new javax.swing.JMenu();
        menuConsultas = new javax.swing.JMenu();
        menuConsultasMatriculados = new javax.swing.JMenuItem();
        menuCinsultasPrecioCurso = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuUtil = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuProcesos.setText("Procesos");
        menuBar.add(menuProcesos);

        menuMaestros.setText("Maestros");
        menuBar.add(menuMaestros);

        menuConsultas.setText("Consultas");

        menuConsultasMatriculados.setText("Matriculados");
        menuConsultasMatriculados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasMatriculadosActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasMatriculados);

        menuCinsultasPrecioCurso.setText("Precio de curso");
        menuCinsultasPrecioCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCinsultasPrecioCursoActionPerformed(evt);
            }
        });
        menuConsultas.add(menuCinsultasPrecioCurso);

        menuBar.add(menuConsultas);

        menuReportes.setText("Reportes");
        menuBar.add(menuReportes);

        menuUtil.setText("Util");
        menuBar.add(menuUtil);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuConsultasMatriculadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasMatriculadosActionPerformed
        mostrarForm(MatriculadosView.class);
    }//GEN-LAST:event_menuConsultasMatriculadosActionPerformed

    private void menuCinsultasPrecioCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCinsultasPrecioCursoActionPerformed
        mostrarForm(PrecioCursoView.class);
    }//GEN-LAST:event_menuCinsultasPrecioCursoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCinsultasPrecioCurso;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuConsultasMatriculados;
    private javax.swing.JMenu menuMaestros;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUtil;
    // End of variables declaration//GEN-END:variables

	private void mostrarForm(Class<?> aClass) {
		try {
			// Variable de control
			JInternalFrame view = null;
			// Buscar instancia
			for (JInternalFrame form : desktopPane.getAllFrames()) {
				if (aClass.isInstance(form)) {
					view = form;
					break;
				}
			}
			// Crear instancia
			if (view == null) {
				view = (JInternalFrame) aClass.getConstructor().newInstance();
				desktopPane.add(view);
				view.setVisible(true);
				view.setMaximum(true);
			}
			view.setSelected(true);
		} catch (Exception e) {
		}
	}

}
